version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choose the Python version you need
    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Assuming you have a requirements.txt file

      # Run tests
      - run:
          name: Run tests
          command: |
            pytest

      # Run code analysis
      - run:
          name: Run code analysis
          command: |
            ruff check .
            ruff format .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
